#!/bin/bash
#environment for the python script
source /opt/gridengine/default/common/settings.sh
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/opt/python/lib
#export PYTHONPATH=/ifs4/BC_PUB/biosoft/pipeline/Package/pymonitor/python
export PYTHONPATH=/ifs4/BC_RD/USER/lizhixin/app/python/python-2.7.12/bin
export PATH=/ifs4/BC_RD/USER/lizhixin/app/python/python-2.7.12/bin:$PATH
#export DRMAA_LIBRARY_PATH=/opt/gridengine/lib/linux-x64/libdrmaa.so
export DRMAA_LIBRARY_PATH=/ifs4/BC_RD/PROJECT/RD_LZX_correction/prj/pymonitor/python2/libdrmaa.so
export PYMONITOR_PY_PATH=/ifs4/BC_RD/PROJECT/RD_LZX_correction/prj/pymonitor/python2/pymonitor.py
export PYMONITOR_SH_PATH=/ifs4/BC_RD/PROJECT/RD_LZX_correction/prj/pymonitor/python2/monitor.new
export PYMONITOR_LOG_PATH=~/.pymonitor.log
export PYMONITOR_CONF_PATH=~/.pymonitor.conf

if [ "$1" = "cron" ]
then
  #echo "TASKLIST & CRONTASK"
  TASKLIST=`ps -o pid,args -u $USER`
  CRONTASK=`echo "$TASKLIST" | awk '/pymonitor.py cron/ {print $1}'`
  if [ -n "$CRONTASK" ]
  then
    #ehco "kill"
    echo kill -9 $CRONTASK
  else
    #echo "run"
    /ifs4/BC_RD/USER/lizhixin/app/python/python-2.7.12/bin/python $PYMONITOR_PY_PATH "$@" 2>$PYMONITOR_LOG_PATH
    #echo $USER >> /ifs5/PC_HUMAN_AP/USER/limiao/temp/monitor/log
  fi
else
  #echo "else"
  /ifs4/BC_RD/USER/lizhixin/app/python/python-2.7.12/bin/python $PYMONITOR_PY_PATH "$@"
fi
